version: "3.8"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
    read_only: true
    mem_limit: 512m
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
